import { allCuz, cuzByNumber, cuzSuraRange, isCuzDataComplete, suraNameFor } from '@/lib/content/cuz';
import { APP_LANGUAGES } from '@/lib/i18n/strings';
import { describe, expect, it } from 'vitest';

/*
 * **These test the committed file, not the code that reads it.** `cuz.data.json` is
 * generated by a script nobody runs on a normal day, so the way it goes wrong is not an
 * exception — it is a file that is quietly short, or missing a language, or holding the
 * first page of a paginated response. Every assertion here is something that was actually
 * wrong at some point while fetching it.
 */

/** The canonical number of ayahs in the Qur'an — an independent check on the boundaries. */
const TOTAL_VERSES = 6236;
/** Pages in the Madani mushaf. Juz share a boundary page, so the sum runs slightly over. */
const MUSHAF_PAGES = 604;

describe('the bundled cüz data', () => {
	it('holds thirty, numbered in order', () => {
		expect(isCuzDataComplete()).toBe(true);
		expect(allCuz()).toHaveLength(30);
	});

	it('accounts for every ayah', () => {
		// If a boundary were wrong, or an entry missing, this total would not land exactly.
		expect(allCuz().reduce((total, entry) => total + entry.verseCount, 0)).toBe(TOTAL_VERSES);
	});

	it('spans the mushaf, about twenty pages at a time', () => {
		const pages = allCuz().map(entry => entry.pageCount);

		// The bug this catches: `findByJuz` is paginated, and taking the page range from the
		// verses it returns gave "2 sayfa" for a cüz that spans twenty.
		expect(Math.min(...pages)).toBeGreaterThanOrEqual(19);
		expect(pages.reduce((total, count) => total + count, 0)).toBeGreaterThanOrEqual(MUSHAF_PAGES);
	});

	it('names its range in every interface language', () => {
		for (const language of APP_LANGUAGES) {
			for (const entry of allCuz()) {
				expect(cuzSuraRange(entry.number, language)).not.toBe('');
			}
		}
	});

	it('carries the design frame’s own example', () => {
		// Q3/Q5 draw cüz 22 as "Ahzâb 31 – Yâsîn 27 · 20 sayfa".
		expect(cuzSuraRange(22, 'tr')).toBe('Ahzâb 31 – Yâsîn 27');
		expect(cuzByNumber(22)?.pageCount).toBe(20);
	});

	it('breaks each cüz into suras that account for exactly its verses', () => {
		/*
		 * The strongest check in this file: the headline range and the per-sura breakdown come
		 * from one `verseMapping`, so if the breakdown were ever derived separately — or a
		 * slice's boundary were off by one — these two numbers would stop agreeing. Nothing on
		 * screen would look wrong; the list would simply be quietly incorrect.
		 */
		for (const entry of allCuz()) {
			const counted = entry.suras.reduce((total, sura) => total + (sura.lastAyah - sura.firstAyah + 1), 0);

			expect(counted).toBe(entry.verseCount);
		}
	});

	it('lists its suras in order and names them in every language', () => {
		for (const entry of allCuz()) {
			expect(entry.suras.length).toBeGreaterThan(0);

			const ids = entry.suras.map(sura => sura.chapterId);

			expect(ids).toEqual([...ids].sort((a, b) => a - b));

			for (const language of APP_LANGUAGES) {
				expect(entry.suras.every(sura => sura.name[language].length > 0)).toBe(true);
			}
		}
	});

	it('carries the design frame’s own breakdown', () => {
		// Q5 draws cüz 22 as Ahzâb 31–73 · Sebe' 1–54 · Fâtır 1–45 · Yâsîn 1–27.
		expect(cuzByNumber(22)?.suras.map(sura => `${sura.name.tr} ${sura.firstAyah}–${sura.lastAyah}`)).toEqual([
			'Ahzâb 31–73',
			"Sebe' 1–54",
			'Fâtır 1–45',
			'Yâsîn 1–27'
		]);
	});

	it('names every one of the 114 suras', () => {
		for (let chapter = 1; chapter <= 114; chapter += 1) {
			expect(suraNameFor(chapter, 'tr'), `sura ${chapter}`).not.toBe('');
		}

		expect(suraNameFor(45, 'tr')).toBe('Câsiye');
		expect(suraNameFor(115, 'tr')).toBe('');
	});

	it('answers nothing for a cüz that does not exist', () => {
		// Clamping to the thirtieth would hide a caller's bug behind a plausible answer.
		expect(cuzByNumber(31)).toBeUndefined();
		expect(cuzByNumber(0)).toBeUndefined();
	});
});
