import data from './sura.data.json';

/**
 * One of the 114 suras as the Quran Foundation describes it — generated by
 * `apps/server/scripts/fetch-cuz-metadata.ts`, never edited by hand.
 *
 * What the reader's sura heading frames: the Arabic name ("الملك"), how many ayahs the sura has
 * ("آياتها ٣٠") and its place in the mushaf ("ترتيبها ٦٧", which is `number`). `bismillahPre`
 * says whether the basmala is set above it — false for Al-Fātiḥa, whose basmala is its first
 * ayah, and for At-Tawba, which has none.
 */
export type SuraInfo = {
	number: number;
	nameArabic: string;
	versesCount: number;
	bismillahPre: boolean;
	/** Where it was revealed — the heading's "Mekkî" / "Medenî". */
	revelationPlace: 'makkah' | 'madinah';
};

const SURAS = data.suras as readonly SuraInfo[];

/** A sura by its number, 1–114; `undefined` outside that. */
export const suraInfo = (number: number): SuraInfo | undefined => SURAS[number - 1];

export const allSuras = (): readonly SuraInfo[] => SURAS;
